# Generated by Django 5.1.4 on 2025-05-31 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scriptures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('bible_text', models.CharField(blank=True, max_length=30, null=True)),
                ('scripture', models.TextField(blank=True, null=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('bible_version', models.CharField(blank=True, choices=[('KJV', 'King James Version'), ('NIV', 'New International Version'), ('ESV', 'English Standard Version'), ('NLT', 'New Living Translation'), ('CSB', 'Christian Standard Bible'), ('NASB', 'New American Standard Bible'), ('NKJV', 'New King James Version')], max_length=30, null=True)),
                ('prayer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('upload_now', 'upload_now'), ('scheduled', 'scheduled'), ('drafts', 'drafts')], max_length=30, null=True)),
                ('like_scripture', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptureComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('comment', models.TextField(blank=True, null=True)),
                ('commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to=settings.AUTH_USER_MODEL)),
                ('scripture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='scriptures.scriptures')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
