# Generated by Django 5.1.4 on 2025-05-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptures', '0002_alter_scriptures_like_scripture'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptures',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
