# Generated by Django 5.1.4 on 2025-05-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptures', '0005_alter_scripturecomment_scripture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripturecomment',
            name='scripture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='scriptures.scriptures'),
        ),
    ]
