# Generated by Django 5.1.4 on 2025-05-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptures', '0006_alter_scripturecomment_scripture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptures',
            name='slug',
        ),
    ]
