# Generated by Django 5.1.4 on 2025-05-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptures', '0007_remove_scriptures_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptures',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
