# Generated by Django 5.1.4 on 2025-07-08 06:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('notify_admin', models.BooleanField(default=True, help_text='Enable to notify the admin after a user submits a donation for verification')),
                ('notify_user', models.BooleanField(default=True, help_text='Send a notification to users when a donation cannot be verified')),
                ('send_user_mail', models.BooleanField(default=True, help_text='Automatically send a thank-you email to users once their donation is verified')),
                ('donation_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card_payment', 'Card Payment')], max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USDDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('account_holder', models.CharField(max_length=225)),
                ('bank_name', models.CharField(max_length=225)),
                ('account_number', models.PositiveIntegerField()),
                ('routing_number', models.PositiveIntegerField()),
                ('swift_code', models.CharField(max_length=225)),
                ('account_type', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NGNDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('account_name', models.CharField(max_length=225)),
                ('bank_name', models.CharField(max_length=225)),
                ('account_number', models.PositiveIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account_name', 'bank_name'), name='unique_account_bank')],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('reference', models.CharField(help_text='Unique transaction reference', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('ng', 'NG'), ('usd', 'USD')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User who initiated the transaction', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction History',
                'verbose_name_plural': 'Transaction Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
