# Generated by Django 5.1.4 on 2025-08-30 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('bank_name', models.CharField(blank=True, max_length=225)),
                ('account_number', models.PositiveIntegerField()),
                ('routing_number', models.PositiveIntegerField()),
                ('swift_code', models.CharField(max_length=225)),
                ('account_type', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('reference', models.CharField(help_text='Unique transaction reference', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('BANK', 'BANK'), ('TRANSFER', 'TRANSFER'), ('CARD', 'CARD')], max_length=255)),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], max_length=10)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User who initiated the transaction', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction History',
                'verbose_name_plural': 'Transaction Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='NGNDonation',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='USDDonation',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
