# Generated by Django 5.1.4 on 2025-11-14 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20251114_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
    ]
