# Generated by Django 5.1.4 on 2025-11-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_amount_delete_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='session_id',
        ),
    ]
