# Generated by Django 5.1.4 on 2025-11-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_remove_donation_reference_remove_donation_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='description',
        ),
    ]
