# Generated by Django 5.1.4 on 2025-11-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_remove_donation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='transaction_type',
            field=models.CharField(choices=[('BANK', 'BANK'), ('BANK_TRANSFER', 'BANK_TRANSFER'), ('CARD', 'CARD'), ('USSD', 'USSD')], max_length=30),
        ),
    ]
