# Generated by Django 4.2.19 on 2025-05-24 16:00

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default=reviews.models.generate_temp_review_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
