# Generated by Django 5.1.4 on 2025-07-01 07:45

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default=reviews.models.generate_temp_review_id, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
