# Generated by Django 4.2.19 on 2025-05-24 16:00

from django.db import migrations

def update_review_ids(apps, schema_editor):
    Review = apps.get_model('reviews', 'Review')
    for i, review in enumerate(Review.objects.all().order_by('created_at'), 1):
        review.id = f"RE-{i:03d}"
        review.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_id'),
    ]

    operations = [
        migrations.RunPython(update_review_ids),
    ]
