# Generated by Django 5.1.4 on 2025-09-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_status',
            field=models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('UNASSIGNED', 'UNASSIGNED')], default='ASSIGNED', max_length=255),
        ),
    ]
