# Generated by Django 5.1.4 on 2025-09-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
