# Generated by Django 5.1.4 on 2025-05-30 02:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_otp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOtp2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('code', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
