# Generated by Django 5.1.4 on 2025-07-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
        ('user', '0003_remove_role_permissions_alter_user_role_and_more'),
    ]

    operations = [
    ]
