# Generated by Django 5.1.4 on 2025-09-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_suspension_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='suspension_reason',
            new_name='deactivation_reason',
        ),
    ]
