# Generated by Django 5.1.4 on 2025-07-22 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddField(
            model_name='user',
            name='is_invitation_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='user.role'),
        ),
    ]
