# Generated by Django 5.1.4 on 2025-05-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_sendotp2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendOtp',
        ),
    ]
