# Generated by Django 4.2.19 on 2025-04-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('deleted', 'deleted'), ('registered', 'registered')], default='registered', max_length=255, null=True),
        ),
    ]
