# Generated by Django 5.1.4 on 2025-10-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_suspension_reason_user_deactivation_reason'),
        ('user', '0004_user_public_id'),
    ]

    operations = [
    ]
