# Generated by Django 5.1.4 on 2025-07-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_permission_user_is_invitation_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_invitation_expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
