# Generated by Django 5.1.4 on 2025-07-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_is_invitation_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_invitation_expired',
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('USED', 'USED')], default='ACTIVE'),
        ),
    ]
