# Generated by Django 5.1.4 on 2025-07-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_is_invitation_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('USED', 'USED')], default='ACTIVE', null=True),
        ),
    ]
