# Generated by Django 5.1.4 on 2025-07-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_invitation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invited_by',
        ),
        migrations.AddField(
            model_name='user',
            name='invite_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
