# Generated by Django 4.2.19 on 2025-06-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_otp_user'),
        ('user', '0009_user_invited_by_alter_user_status_userinvitation'),
    ]

    operations = [
    ]
