# Generated by Django 5.1.4 on 2025-05-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_otp_user'),
        ('user', '0009_user_invited_by_alter_user_status_userinvitation'),
    ]

    operations = [
    ]
