# Generated by Django 5.1.4 on 2025-07-23 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_invited_by_user_invite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternative_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_role', to='user.role'),
        ),
    ]
