# Generated by Django 5.1.4 on 2025-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_alternative_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('DELETED', 'DELETED'), ('REGISTERED', 'REGISTERED'), ('INVITED', 'INVITED')], default='REGISTERED', max_length=255, null=True),
        ),
    ]
