# Generated by Django 4.2.19 on 2025-06-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20250613_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvitation',
            old_name='code',
            new_name='token',
        ),
    ]
