# Generated by Django 4.2.19 on 2025-06-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_code_userinvitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitation',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
