# Generated by Django 5.1.4 on 2025-09-14 22:51

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspirationalPictures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images/inspirational_pic/')),
                ('source', models.CharField(blank=True, db_index=True, help_text='Source of the inspirational picture', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('upload_now', 'upload_now'), ('scheduled', 'scheduled'), ('drafts', 'drafts')], db_index=True, max_length=225, null=True)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text="Datetime for scheduling the upload (used only for 'Schedule for Later' status)", null=True)),
                ('like_inspirational_pic', models.ManyToManyField(blank=True, related_name='like_inspirational_pic', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspirational Picture',
                'verbose_name_plural': 'Inspirational Pictures',
            },
        ),
        migrations.CreateModel(
            name='TextTestimony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('title', models.CharField(help_text='Enter Title', max_length=255)),
                ('category', models.CharField(choices=[('Healing', 'Healing'), ('Finance', 'Finance'), ('Breakthrough', 'Breakthrough'), ('Protection', 'Protection'), ('Salvation', 'Salvation'), ('Deliverance', 'Deliverance'), ('Restoration', 'Restoration'), ('Spiritual_growth', 'Spiritual growth'), ('Education', 'Education'), ('Career', 'Career'), ('Other', 'Other')], db_index=True, max_length=50)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('content', models.TextField()),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], db_index=True, default='PENDING', max_length=20)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoTestimony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('title', models.CharField(help_text='Enter Title', max_length=255)),
                ('category', models.CharField(choices=[('Healing', 'Healing'), ('Finance', 'Finance'), ('Breakthrough', 'Breakthrough'), ('Protection', 'Protection'), ('Salvation', 'Salvation'), ('Deliverance', 'Deliverance'), ('Restoration', 'Restoration'), ('Spiritual_growth', 'Spiritual growth'), ('Education', 'Education'), ('Career', 'Career'), ('Other', 'Other')], db_index=True, max_length=50)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('source', models.CharField(blank=True, help_text='Video source', max_length=255, null=True)),
                ('upload_status', models.CharField(choices=[('upload_now', 'upload_now'), ('scheduled', 'scheduled'), ('drafts', 'drafts')], max_length=225)),
                ('video_file', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('auto_generate_thumbnail', models.BooleanField(default=True, help_text='Auto-generate thumbnail if no upload')),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text="Datetime for scheduling the upload (used only for 'Schedule for Later' status)", null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('object_id', models.UUIDField()),
                ('content', models.TextField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='testimonies.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='testimonies_content_7c5668_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='testimonies_content_49f7df_idx')],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='testimonies_content_97a6e8_idx')],
            },
        ),
    ]
