# Generated by Django 5.1.4 on 2025-01-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='share',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
