# Generated by Django 5.1.4 on 2025-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttestimony',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
