# Generated by Django 5.1.4 on 2025-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotestimony',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videotestimony',
            name='video_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
