# Generated by Django 5.1.4 on 2025-07-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ManyToManyField(blank=True, to='testimonies.comment'),
        ),
    ]
