# Generated by Django 5.1.4 on 2025-11-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttestimony',
            name='category',
            field=models.CharField(choices=[('Healing', 'Healing'), ('Finance', 'Finance'), ('Breakthrough', 'Breakthrough'), ('Protection', 'Protection'), ('Salvation', 'Salvation'), ('Deliverance', 'Deliverance'), ('Restoration', 'Restoration'), ('Spiritual_growth', 'Spiritual growth'), ('Education', 'Education'), ('Career', 'Career'), ('Faith', 'Faith'), ('Marriage Restoration', 'Marriage Restoration'), ('Other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='videotestimony',
            name='category',
            field=models.CharField(choices=[('Healing', 'Healing'), ('Finance', 'Finance'), ('Breakthrough', 'Breakthrough'), ('Protection', 'Protection'), ('Salvation', 'Salvation'), ('Deliverance', 'Deliverance'), ('Restoration', 'Restoration'), ('Spiritual_growth', 'Spiritual growth'), ('Education', 'Education'), ('Career', 'Career'), ('Faith', 'Faith'), ('Marriage Restoration', 'Marriage Restoration'), ('Other', 'Other')], db_index=True, max_length=50),
        ),
    ]
