# Generated by Django 5.1.4 on 2025-07-09 04:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0002_alter_inspirationalpictures_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspirationalpictures',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images/inspirational_pic/'),
        ),
    ]
