# Generated by Django 5.1.4 on 2025-07-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0002_alter_texttestimony_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotestimony',
            name='rejection_reason',
        ),
    ]
