# Generated by Django 5.1.4 on 2025-08-15 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testimonies', '0003_rename_text_comment_content_remove_comment_reply_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='testimonies_content_7c5668_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['content_type', 'object_id'], name='testimonies_content_49f7df_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['content_type', 'object_id'], name='testimonies_content_97a6e8_idx'),
        ),
    ]
