# Generated by Django 5.1.4 on 2025-02-13 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0003_alter_videotestimony_upload_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationalPictures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('thumbnail', models.ImageField(upload_to='inspirational_picture/')),
                ('status', models.CharField(choices=[('upload_now', 'upload_now'), ('schedule_for_later', 'schedule_for_later'), ('drafts', 'drafts')], max_length=225)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text="Datetime for scheduling the upload (used only for 'Schedule for Later' status)", null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
