# Generated by Django 5.1.4 on 2025-06-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0003_alter_texttestimony_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set(),
        ),
    ]
