# Generated by Django 5.1.4 on 2025-03-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0004_inspirationalpictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspirationalpictures',
            options={'verbose_name': 'Inspirational Picture', 'verbose_name_plural': 'Inspirational Pictures'},
        ),
    ]
