# Generated by Django 5.1.4 on 2025-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0004_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttestimony',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videotestimony',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
