# Generated by Django 5.1.4 on 2025-08-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0004_comment_testimonies_content_7c5668_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
