# Generated by Django 5.1.4 on 2025-08-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0005_comment_reply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttestimony',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='texttestimony',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='videotestimony',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='videotestimony',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
