# Generated by Django 4.2.19 on 2025-04-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0005_alter_inspirationalpictures_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_admin', models.BooleanField(default=True)),
            ],
        ),
    ]
