# Generated by Django 5.1.4 on 2025-06-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0005_texttestimony_views_videotestimony_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttestimony',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='videotestimony',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
