# Generated by Django 5.1.4 on 2025-08-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0006_texttestimony_comment_count_texttestimony_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttestimony',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='texttestimony',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='videotestimony',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='videotestimony',
            name='like_count',
        ),
    ]
