# Generated by Django 5.1.4 on 2025-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0006_testimonysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotestimony',
            name='source',
            field=models.CharField(blank=True, help_text='Video source', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videotestimony',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='videos/'),
        ),
    ]
