# Generated by Django 5.1.4 on 2025-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0006_alter_texttestimony_views_alter_videotestimony_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationalpictures',
            name='source',
            field=models.CharField(blank=True, help_text='Source of the inspirational picture', max_length=255, null=True),
        ),
    ]
