# Generated by Django 5.1.4 on 2025-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0007_inspirationalpictures_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationalpictures',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL of the thumbnail image', null=True),
        ),
        migrations.AlterField(
            model_name='inspirationalpictures',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='inspirational_picture/'),
        ),
    ]
