# Generated by Django 5.1.4 on 2025-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0007_alter_videotestimony_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttestimony',
            name='upload_status',
            field=models.CharField(blank=True, choices=[('upload_now', 'upload_now'), ('schedule_for_later', 'schedule_for_later'), ('drafts', 'drafts')], max_length=50, null=True),
        ),
    ]
