# Generated by Django 5.1.4 on 2025-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0008_inspirationalpictures_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationalpictures',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
