# Generated by Django 5.1.4 on 2025-05-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0008_texttestimony_upload_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttestimony',
            name='upload_status',
        ),
    ]
