# Generated by Django 5.1.4 on 2025-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0009_remove_texttestimony_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttestimony',
            name='category',
            field=models.CharField(choices=[('healing', 'healing'), ('finance', 'finance'), ('breakthrough', 'breakthrough'), ('protection', 'protection'), ('salvation', 'salvation'), ('deliverance', 'deliverance'), ('restoration', 'restoration'), ('spiritual_growth', 'spiritual growth'), ('education', 'education'), ('career', 'career'), ('other', 'other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='texttestimony',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='videotestimony',
            name='category',
            field=models.CharField(choices=[('healing', 'healing'), ('finance', 'finance'), ('breakthrough', 'breakthrough'), ('protection', 'protection'), ('salvation', 'salvation'), ('deliverance', 'deliverance'), ('restoration', 'restoration'), ('spiritual_growth', 'spiritual growth'), ('education', 'education'), ('career', 'career'), ('other', 'other')], db_index=True, max_length=50),
        ),
    ]
