# Generated by Django 5.1.4 on 2025-06-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0009_inspirationalpictures_shares_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspirationalpictures',
            name='status',
            field=models.CharField(blank=True, choices=[('upload_now', 'upload_now'), ('scheduled', 'scheduled'), ('drafts', 'drafts')], max_length=225, null=True),
        ),
    ]
