# Generated by Django 5.1.4 on 2025-05-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0010_alter_texttestimony_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotestimony',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
