# Generated by Django 5.1.4 on 2025-06-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0010_alter_inspirationalpictures_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspirationalpictures',
            name='thumbnail_url',
        ),
    ]
