# Generated by Django 5.1.4 on 2025-05-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0011_videotestimony_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotestimony',
            name='is_published',
        ),
    ]
