# Generated by Django 5.1.4 on 2025-07-01 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0011_remove_inspirationalpictures_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='testimonies.comment'),
        ),
    ]
