# Generated by Django 5.1.4 on 2025-07-03 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0012_comment_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_like_comment',
            field=models.ManyToManyField(blank=True, related_name='user_like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
