# Generated by Django 5.1.4 on 2025-07-03 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0013_comment_user_like_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationalpictures',
            name='like_inspirational_pic',
            field=models.ManyToManyField(blank=True, related_name='like_inspirational_pic', to=settings.AUTH_USER_MODEL),
        ),
    ]
