# Generated by Django 5.1.4 on 2025-07-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0014_inspirationalpictures_like_inspirational_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ManyToManyField(blank=True, related_name='replies', to='testimonies.comment'),
        ),
    ]
