# Generated by Django 5.1.4 on 2025-07-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0015_remove_comment_reply_to_comment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ManyToManyField(blank=True, to='testimonies.comment'),
        ),
    ]
